FROM posit/r-base:4.5-noble

RUN apt-get update && apt-get install -y \
  git \
  libcurl4-gnutls-dev \
  libssl-dev \
  libxml2-dev \
  locales \
  && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
  && locale-gen \
  && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8

# We use this repo for package installs to use pre-built binaries
ENV CRAN="https://p3m.dev/cran/__linux__/noble/latest"

## options(repos = c(CRAN = sprintf("https://packagemanager.posit.co/cran/latest/bin/linux/noble-%s/%s", R.version["arch"], substr(getRversion(), 1, 3))))


RUN Rscript -e 'install.packages(c("rsconnect", "renv", "remotes", "jsonlite"), repos = Sys.getenv("CRAN"))'

ARG GIT_BRANCH=main

WORKDIR /workspace

COPY DESCRIPTION NAMESPACE ./
RUN Rscript -e 'remotes::install_deps(".", dependencies = TRUE, upgrade = "never", repos = Sys.getenv("CRAN"))'

COPY . .
RUN Rscript -e "remotes::install_github('posit-dev/chronicle-reports@${GIT_BRANCH}', upgrade = 'never')"

COPY manifests.R /manifests.R

CMD ["Rscript", "/manifests.R"]
